apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myrs
 labels:
  name: webserver
spec:
 Replicas: 3
 selectors:
  matchLabels:
   type: webserver
 template:
  metadata:
   name: Pod
    labels:
     name: webserver
  spec:
    containers:
    - name: myn1
      image: mynginx
      
